export const locations = [
    'All', 
    'Machakos Town',
    'Kenya Israel', 
    'Isuzu', 
    'Miwani', 
    'ABC', 
    'Katoloni', 
    'Machakos University', 
    'Eastleigh', 
    'Katelembu', 
    'Machakos Girls', 
    'Sokoni', 
    'Mtituni', 
    'Sweetwaters', 
    'Tumba', 
    'Scotts University', 
    'Machakos Academy',
    'Masii'
];
export const houseTypes = ['All', 'Bedsitter', 'Single Room', '1 Bedroom', '2 Bedroom', 'House', 'Hostel', 'Business'];
export const featureOptions = [
    'Tiled Floors', 
    'Constant Water', 
    'Parking', 
    'Balcony', 
    'Secure Compound', 
    'Token Electricity',
    'Ladies Only',
    'Gents Only',
    'Inside Campus',
    'Outside Campus',
    'Shared Rooms',
    'Private Rooms',
];
